name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: ["Dev", "Stage", "Nexus"]
          
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
    - name: Install root dependencies
      run: npm install
    - name: Install UI dependencies
      run: |
        cd packages/ui
        npm install
    - name: Set environment variables
      run: |
        if [ "${{ matrix.environment }}" == "Dev" ]; then
          echo "SERVER_HOST=${{ vars.SERVER_HOST_DEV }}" >> $GITHUB_ENV
          echo "SERVER_PID=${{ vars.SERVER_PID_DEV }}" >> $GITHUB_ENV
          echo "SERVER_UID=${{ vars.SERVER_UID_DEV }}" >> $GITHUB_ENV
          echo "SERVER_TOKEN=${{ secrets.SERVER_TOKEN_DEV }}" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "Stage" ]; then
          echo "SERVER_HOST=${{ vars.SERVER_HOST_ST }}" >> $GITHUB_ENV
          echo "SERVER_PID=${{ vars.SERVER_PID_ST }}" >> $GITHUB_ENV
          echo "SERVER_UID=${{ vars.SERVER_UID_ST }}" >> $GITHUB_ENV
          echo "SERVER_TOKEN=${{ secrets.SERVER_TOKEN_ST }}" >> $GITHUB_ENV
        elif [ "${{ matrix.environment }}" == "Nexus" ]; then
          echo "SERVER_HOST=${{ vars.SERVER_HOST_NEX }}" >> $GITHUB_ENV
          echo "SERVER_PID=${{ vars.SERVER_PID_NEX }}" >> $GITHUB_ENV
          echo "SERVER_UID=${{ vars.SERVER_UID_NEX }}" >> $GITHUB_ENV
          echo "SERVER_TOKEN=${{ secrets.SERVER_TOKEN_NEX }}" >> $GITHUB_ENV
        fi
    - name: Start server
      run: |
        cd packages/ui/test/plugin
        npm install
        node server.js -sh $SERVER_HOST -spid $SERVER_PID -muid $SERVER_UID -st $SERVER_TOKEN &
    - name: Start chat/webpack run
      run: |
        cd packages/ui
        npx webpack --env plugin=http://localhost:3333 &
    - name: Install test dependencies and run tests
      run: |
        cd packages/ui/test/ui_test
        npm install
        npx playwright install
        npm test
    - name: Upload test results on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: failed-test-results
        path: packages/ui/test/ui_test/test-results/
